# Generated by Django 5.1.7 on 2025-03-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeptYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('num_courses', models.IntegerField()),
                ('in_degree', models.FloatField()),
                ('out_degree', models.FloatField()),
                ('density', models.FloatField()),
                ('keywords', models.TextField()),
                ('similar_depts', models.TextField()),
                ('courses_added', models.TextField()),
                ('courses_removed', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
