# Generated by Django 5.1.7 on 2025-03-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_deptyear_delete_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deptyear',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
