# Generated by Django 5.1.7 on 2025-03-20 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_deptyear_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deptyear',
            unique_together={('dept_name', 'year')},
        ),
    ]
