# Generated by Django 5.1.7 on 2025-04-02 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_deptyear_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deptyear',
            old_name='in_degree',
            new_name='max_indegrees',
        ),
        migrations.RenameField(
            model_name='deptyear',
            old_name='out_degree',
            new_name='max_outdegrees',
        ),
        migrations.RemoveField(
            model_name='deptyear',
            name='courses_added',
        ),
        migrations.RemoveField(
            model_name='deptyear',
            name='courses_removed',
        ),
        migrations.RemoveField(
            model_name='deptyear',
            name='num_courses',
        ),
        migrations.AddField(
            model_name='deptyear',
            name='graph_representation',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
